### ISSUE TITLE
adding graphics and Level System

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#10]
## Value proposition

As a student
I want to have fun while learning
in order to keep being motivated

## Description

![enemy](https://user-images.githubusercontent.com/125862830/233053757-8bbcf10e-97df-4c7d-8ef8-3489f2722fd4.png)

## Acceptance criteria

- [ ] I want to see in what level and stage I am in
- [ ] For each level and stage I want to see a different background image
- [ ] I want to see the picture of my enemy
- [ ] I want to see the health of the enemy

## Tasks

- [ ] the Level and Stage for the chosen avatar is written to the database
- [ ] create a "ShowImage.js" component to display the background image, depending on level and stage
- [ ] create a "ShowEnemy.js" component to display the current Enemy
- [ ] make sure the background Image changes when the stage changes
- [ ] show the enemy's health and for each right letter, subtract health points
- [ ] show next enemy when he has no health left

Size:

**Comment by BenRodProd** [comment]
thank you for the suggestion...
