### ISSUE TITLE
Show Library

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#11]
## Value proposition

As a student
I want to organize my vocabulary in a Library
in order to be able to learn different topics

## Description

![Library](https://user-images.githubusercontent.com/125862830/233054399-37880ec9-7fe0-48e5-a3ba-aa8cf93661f1.png)

## Acceptance criteria

- [ ] the books i have added should be shown as a virtuel bookshelf
- [ ] when clicking on the book i want to go to the ShowBook-view 
- [ ] i want to be able to add a new book

## Tasks

- [ ] create a ShowLibrary component 
- [ ] create a horizontal list of books, in the look of bookbacks
- [ ] create a "add new book" button which links to the "ShowBook" component

Size: M

**Comment by gaborrubus** [comment]
With the changed description Photo LGTM !
