### ISSUE TITLE
RPG ELEMENTS

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#12]
## Value proposition

As a student
I want to have fun while learning
in order to stay motivated

## Description

![userStory2](https://user-images.githubusercontent.com/125862830/233103946-959e0aab-f13d-4644-98b1-fa69c4fc02e7.png)

## Acceptance criteria

- [ ] a health, stamina and armor slider should display the players status
- [ ] when entering a wrong letter the armor or, if no armor is left, health should decrease

## Tasks

- [ ] implement inputs "range" for health, armor and stamina
- [ ] decrease it when a wrong letter is entered
- [ ] Save health and stamina status in user data dummy

Size: S

**Comment by Satttoshi** [comment]
Cool Idea! 

You should specify your value proposition more, you have to describe your feature, so I can get a grasp of any value.

As a student
I want to lose player stats when typing wrong letters
So the gamification helps me to stay motivated

Good luck developing, that's a very helpful creative project you got here! :rocket:

**Comment by BenRodProd** [comment]
thank you... will apply the changes

**Comment by FrankSiyli** [comment]
LGTM
