### ISSUE TITLE
Enemy Health and first graphics

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#13]
## Value proposition

As a student
I want to see a benefit from entering the right letter and nice graphics
in order to stay motivated

## Description

![userStory2-2](https://user-images.githubusercontent.com/125862830/233111913-85780d21-5e72-4ad9-af8c-c59dae755072.png)

## Acceptance criteria

- [ ] the health of the enemy is displayed
- [ ] each time a correct letter is entered, the enemy's health should decrease
- [ ] the picture and name of the enemy is shown
- [ ] when the enemy has no health, the next enemy should show up
- [ ] a background image should be displayed

## Tasks

- [ ] implement an input "range" slider to show enemy's health
- [ ] create array of enemy objects
- [ ] show enemy's name
- [ ] show enemy's image
- [ ] when correct letter is entered, the enemy's health should decrease
- [ ] when enemy's health is 0, show next enemy's image & name
- [ ] implement the background-image

Size: M

**Comment by CJAkkuec** [comment]
Nice work!

> when the enemy has no health, the next enemy should show up
I'd argue this is a different User Story (switching out enemies, etc), along with this, as well ⬇️
> when enemy's health is 0, show next enemy's image & name

>  implement an input "range" slider to show enemy's health
Perhaps you may want to use the HTML element `<progress>` instead. ;)

**Comment by BenRodProd** [comment]
ok, the progress looks better, thanks...
