### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#14]
## Value proposition

As a student
I want to see my avatar
in order to identify with the main character

## Description

![Screenshot 2023-04-20 at 09 02 26](https://user-images.githubusercontent.com/125862830/233286583-aa1a9698-fa07-45b5-8310-e64687811f86.png)

## Acceptance criteria

- [ ] the picture of the avatar is shown

## Tasks

- [ ] integrate the avatar in the user dummy data
- [ ] create a ShowAvatar component and integrate it into the main.js
Size: S

**Comment by CJAkkuec** [comment]
Good job, nice and concise. :)

**Comment by BenRodProd** [comment]
thank you
