### ISSUE TITLE
Map Integration

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#16]
## Value proposition

As a student
I want to see the story progressing
in order to know in which level i am in and what is the next level

## Description

![Screenshot 2023-04-20 at 11 15 59](https://user-images.githubusercontent.com/125862830/233320597-ae1b3394-792b-4d8c-8312-d8990a3f9326.png)

## Acceptance criteria

- [ ] a map is shown
- [ ] it should show where i am according to the level

## Tasks

- [ ] create a ShowMap component
- [ ] create an Array of image sources for different stages of the map
- [ ] link the current level to the image sources

Size: S

**Comment by CJAkkuec** [comment]
> As a student
> I want to see the story progressing
> in order to know in which level i am in and what is the next level

I think the value proposition isn't fully congruent with the User Story. I wouldn't refer to it as story progression, but level progression. You don't strictly need to progress in levels for a story to progress from a game design perspective.

I'd probably suggest putting the map somewhere else as well, seeing as how it's not that important to the game mechanics, but it's in a high-attention spot.

>  a map is shown
> it should show where i am according to the level

I think the purpose of the map and acceptance criteria aren't clear enough.
What do I need it for? What is acceptable behavior?
Does it show my avatar on a bigger map? Does it show a level map? Is it just a flavor image?

>  create a ShowMap component
>  create an Array of image sources for different stages of the map
>  link the current level to the image sources

I'd suggest something like LevelMap, probably.

I'm a little unsure what the second and third task is referring to. What does stages mean? What does "link the current level" mean?

You're doing really, really well. This User Story just needs a little more love and thought put into it.

**Comment by BenRodProd** [comment]
thank you... I get what you mean and edited it accordingly. but it is quite hard to decide, where to put the map on the screen, as things like an inventory will be shown, too... I'll leave it there for now, if you don't mind...

**Comment by gaborrubus** [comment]
It looks good to me.
