### ISSUE TITLE
View of Book

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#17]
## Value proposition

As a student 
I want to see a list of my 
in order to stay organised

## Description

![Screenshot 2023-04-20 at 14 12 09](https://user-images.githubusercontent.com/125862830/233362280-dd2db053-d9aa-4f8d-aaaf-5e6dab42a4a2.png)

## Acceptance criteria

- [ ] a list of the vocabulary is shown

- [ ] by clicking on the add button, i can add an entry to the book (user story 7.1)
- [ ] a statistic is shown, how many entries I have in this book
## Tasks

- [ ] create the /library/book route
- [ ] add an index.js
- [ ] display the list of entries to the dummy data

- [ ] make a field displaying the total entries
Size: M

**Comment by CJAkkuec** [comment]
I think we're running into some compositional challenges here. I'd suggest detangling the structure a little. You'd want a library page. There you have a form that lets you create wisdoms. Clicking an edit button (or similar) on the e.g. wisdom card will allow you to edit it. There could also be a delete button.
These are all different User Stories. 

A library page displaying wisdoms. (Size: S)
A form letting you create wisdoms. (Size: M)
An edit feature. (Size: M/L)
A delete feature. (Size: S)

Editing especially is non-trivial.

**Comment by CJAkkuec** [comment]
> As a student
> I want to see a list of my
> in order to stay organised
A list of my ... ? What?? The anticipation is killing me!!!

LGTM otherwise.
