### ISSUE TITLE
Integrate a storyline 

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#18]
## Value proposition

As a student
I want to get more the feeling of roleplaying
in order to be entertained while learning

## Description

![Screenshot 2023-04-20 at 14 33 09](https://user-images.githubusercontent.com/125862830/233367118-13a61da7-5c64-46c6-9189-86c36bc343fd.png)

## Acceptance criteria

- [ ] show a popup everytime the stage (4 stages for each level) changes
- [ ] In this popup, display the map, where we are and the part of the story
- [ ] The story should have an audio narrator and text
- [ ] the map should show where the player can go next and by clicking on the path the according level/stage should be displayed

## Tasks

- [ ] create a popup and use the map component to render the current position
- [ ] play audio file of the narrator and display the text
- [ ] create the story data with audio-file sources and map positions
- [ ] let the narrator tell the player at the end, he has to choose between xy options ("do you want to go right or left?")

Size: L

**Comment by gaborrubus** [comment]
LGTM
