### ISSUE TITLE
Add Form

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#19]
## Value proposition

As a student
I want to enter vocabulary
in order to learn them

## Description

![Image](https://user-images.githubusercontent.com/125862830/233381788-43166ea9-b3d8-49e4-bce2-e19201158c58.png)

[image of wireframe]

### on the edit page
- [ ] an input form is shown
- [ ] i can type in answers and questions
- [ ] i can choose which category it belongs to with a dropdown menu
- [ ] i can choose the benefits belonging to this question (more health, armor or stamina) or let the app pick one randomly

## Tasks

- [ ] create Form with 4 input fields
- [ ] create new Object from the submit in the Library-Array
- [ ] create a route "/library/books/add" with index.js

Size: M

**Comment by KevinBlbd** [comment]
Looks good to me!
