### ISSUE TITLE
Edit Wisdom Page

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#20]
## Value proposition

As a student
I want to edit the vocabulary
in order to change the typos i made

## Description

![Screenshot 2023-04-20 at 15 43 52](https://user-images.githubusercontent.com/125862830/233385393-d5b417eb-9619-4061-b54b-5e46b4c15df7.png)

## Acceptance criteria

- [ ] by clicking on the card in "library/book/index.js" I get to a form to edit the card

## Tasks

- [ ] make a link from the "library/book/index.js" to the route of the question id
- [ ] make an edit form like the add new card form 
- [ ] when saved push route back to the book view

Size: M

**Comment by CJAkkuec** [comment]
You should probably mention in your acceptance criteria that the user should be routed back to the overview.

**Comment by CJAkkuec** [comment]
LGTM 🚀
