### ISSUE TITLE
Delete wisdom

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#21]
## Value proposition

As a student
I want to delete a question
in order to remove unwanted questions

## Description
![Screenshot 2023-04-20 at 15 51 23](https://user-images.githubusercontent.com/125862830/233388181-6ffc3908-4959-42a5-8f92-a0d35099526d.png)

## Acceptance criteria

- [ ] A delete Button is shown on the Edit Page
- [ ] when clicking it, the entry should be deleted and the user should be taken back to the book view

## Tasks

- [ ] add a delete button
- [ ] delete the entry when clicked
- [ ] execute a "router.push("/")

Size: S

**Comment by CJAkkuec** [comment]
Technically, this looks good and I'd approve it. Here's a suggestion tough: sometimes accidental clicks happen, especially for users with limited or altered mobility. Perhaps you want to include a modal (pop-up) that checks whether the user is really sure they want to delete the entry.
