### ISSUE TITLE
audio integration

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#22]
## Value proposition

As a student
I want to have background sounds and music 
in order to dive more into the story, what is a game without sound?

## Description

Imagine sound and music that take you more into the scene you are in.

## Acceptance criteria

- [ ] for each level a different background sound (birds in the meadows, wind in the forest, etc) is played
- [ ] for each situation a different music is played (calm while the story is told, dramatic while fighting, etc) 

## Tasks

- [ ] connect the levels and situations with different audio files

Size: M

**Comment by onemanwenttomow** [comment]
Nice idea. I would suggest allowing the user to have some way of muting the sound if they want to. That could be a general mute button accessible on all pages, or maybe having a user settings page/popup where they can turn it on and off (this would be a whole new user story)

**Comment by BenRodProd** [comment]
yeah, it's US 16... but thx...
