### ISSUE TITLE
Avatar Level System and XP

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#23]
## Value proposition

As a student
I want my avatar to level up when reached an amount of XP
in order to stay motivated to continue the game

## Description
![knightevolve](https://user-images.githubusercontent.com/125862830/233594159-8224fcdf-8a41-4e9e-863e-890130f75c72.png)

## Acceptance criteria

- [ ] show XP under Avatar Image
- [ ] define for every enemy, how many xp you can get (In the Enemy-Array)
- [ ] define for each level of the avatar, when it will level up (In a new avatarLevelSystem-Array)

## Tasks

- [ ] create a progress-Element under the avatar, that shows how many xp it has and indicates, when the next level-up will happen
- [ ] update the ShowAvatar component, so it takes the current avatar picture as a prop

Size: M

**Comment by onemanwenttomow** [comment]
Does the user object playing the game have a property for the number of XP points they have already achieved? 

Otherwise LGTM.
