### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#24]
## Value proposition

As a student
I want to be able to turn down the music, fx and narrator volume
in order to listen to my own music or play the game in silence

## Description
![Screenshot 2023-04-21 at 11 49 58](https://user-images.githubusercontent.com/125862830/233605674-2e51a2c2-20e4-4284-b465-7b5bcf1c7bdc.png)

## Acceptance criteria

- [ ] at the navigation bar, a settings link is shown and linked to the settings page
- [ ] i can set the volume for music, fx and narrator
- [ ] it will be set as i chose

## Tasks

- [ ] implement the "/settings/index.js" in the navigation bar
- [ ] create the "/settings/index.js" with three input "range" sliders
- [ ] save the settings of the sliders in the user database
- [ ] connect the musicVolume, narratorVolume and fxVolume from the user database to the audio elements

Size: S

**Comment by onemanwenttomow** [comment]
LGTM
