### ISSUE TITLE
create inventory

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#25]
## Value proposition

As a student
I want to be able to collect items and use them
in order to have a more RPG-like feeling

## Description

[image of wireframe]

## Acceptance criteria

- [ ] an inventory is displayed
- [ ] i can click on an item and see an effect
- [ ] for every 20 wisdoms entered in the library, the player should get a random item (just write it into database for now)

## Tasks

- [ ] create inventory box on "jouney/index.js"
- [ ] display all items the user has (database) in this box
- [ ] by clicking on it, the effect should be seen (health portion -> more health, helmet / shield -> more armor)
- [ ] create a counter and randomizer on the "library/book/index.js" that writes for every 20 entered questions/answers an item into the user database ( [ { avatar: { items : ["health", etc] } } ] )

Size: M

**Comment by PacoSchwab** [comment]
LGTM (maybe you could specify the expression "...see an effect" if you like) :)
