### ISSUE TITLE
item popup

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#26]
## Value proposition

As a student
I want to see what item i get by adding questions to the library and how far in the storyline i can get with it
in order to be motivated to add more questions

## Description
![Screenshot 2023-04-21 at 12 47 47](https://user-images.githubusercontent.com/125862830/233617671-2fc31e64-4e47-4b54-a492-e63279519d1b.png)

## Acceptance criteria

- [ ] make a popup appear in the "library/books/add.js"
- [ ] It should show the item the user gets
- [ ] it should show what percentage of the story the user can play with the entered amount of questions (ap. 200 to finish story)

## Tasks

- [ ] create the popup
- [ ] get from the new item from the randomizer (US 19)
- [ ] display the current health/armor status
- [ ] show the inventory
- [ ] calculate and show what percentage of the story the user is able to access

Size: M

**Comment by KevinBlbd** [comment]
LGTM
