### ISSUE TITLE
Entry Form

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#3]
## Value proposition

As a student
I want to enter vocabulary
in order to be questioned later on

## Description

![WisdomForm](https://user-images.githubusercontent.com/125862830/233018683-1141abd1-efe9-4a80-8b02-d115456ac37a.png)

## Acceptance criteria

- [ ] a input form is shown where 
- [ ] i can type in answers and questions
- [ ] i can choose which category it belongs to

## Tasks

- [ ] create Form with 3 input fields
- [ ] create Object from the submit

Size: m
