### ISSUE TITLE
adding damage display

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#34]
## Value proposition

As a student
I want to see the damage the enemy or I get by wrong / right answers
in order to immediately see consequences of my actions  

## Description

<img width="222" alt="Screenshot 2023-04-27 at 08 22 21" src="https://user-images.githubusercontent.com/125862830/234776945-3217359c-978d-439d-8cb7-8f3eeba43df2.png">

## Acceptance criteria

- [ ] when entered right letter, a number of damage points should be displayed at the enemy
- [ ] when entered wrong letter, a number of damage points should be displayed at the players avatar

## Tasks

- [ ] create EnemyDamage Component and pass the "damage" state as props
- [ ] create UserDamage Component and pass the "damage" state as props

Size: S

**Comment by mulewile** [comment]
LGTM
