### ISSUE TITLE
Mobile friendly Input

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#35]
## Value proposition

As a student
I want to enter answers without an annoying virtual keyboard taking half the screen
in order to use the app on my mobile device

## Description

<img width="217" alt="Screenshot 2023-04-27 at 08 31 40" src="https://user-images.githubusercontent.com/125862830/234778733-1e1ce6fd-5f97-4bf0-9971-0f55897c4c90.png">

## Acceptance criteria

- [ ] under the answer field a scrollable choice of letters is shown
- [ ] when selecting a letter, it should be inserted in the selected input field

## Tasks

- [ ] search for component to implement scrollable letterchoice
- [ ] rewrite the inputfields to take this as input
Size: M

**Comment by BenRodProd** [comment]
scrollable letterchoices are a mess, so now it is a choice of 9 random letters...
