### ISSUE TITLE
Database Integration

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#4]
## Value proposition

As a student
I want the questions to be memorized
in order to keep them

## Description

![Database-partial](https://user-images.githubusercontent.com/125862830/233022835-ef387dec-ce3b-4e27-b9a9-620f60252214.png)

## Acceptance criteria

- [ ] the question, the answer, the category and benefits should be saved

## Tasks

- [ ] creating a MongoDB Database
- [ ] create the ability to write to that database
- [ ] create the structure of each entry

Size: m

**Comment by CJAkkuec** [comment]
I'd probably disagree with the size there ;). I'd suggest expecting a size L feature rather than M.
