### ISSUE TITLE
game logic

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#45]
## Value proposition

As a user
I want to feel the "game logic"
in order to stay motivated

## Description

![Screenshot 2023-05-04 at 18 50 27](https://user-images.githubusercontent.com/125862830/236272002-470026e6-1420-47d1-b632-2a5da91b2e35.png) ![Screenshot 2023-05-04 at 18 51 17](https://user-images.githubusercontent.com/125862830/236272169-1c06aabd-98d2-468b-9ab0-fca77fd58e06.png) ![Screenshot 2023-05-04 at 18 54 16](https://user-images.githubusercontent.com/125862830/236272877-fdb5bb96-b517-4e0f-8d83-b95b50b3f818.png)

## Acceptance criteria

- [ ] the user can choose an avatar for each book
- [ ] entering vocabulary should affect the avatars stats (health)
- [ ] when choosing a book and going back to the main game, this book should be the basis of the game (only wisdoms of this book are tested and the level, stage, health etc. is saved inside the user database 

## Tasks

- [ ] create a "choose avatar" page when adding a book and save the avatar in the user data and display the avatar in the book
- [ ] show the avatars health on the "add wisdom" page and increase it for every input
- [ ] when leaving an empty book, show a popup that no empty books will be saved
- [ ] when leaving a book, inform the user, that this book now is the basis of the main game

Size: M

**Comment by CJAkkuec** [comment]
Hello there,
I have some concerns, which are a little bit abstract and concerning game design more than this user story per se.

> As a user
> I want to feel the "game logic"
> in order to stay motivated

I think the value proposition isn't really getting across the benefit of this particular user story. What's the journey, here?

>  the user can choose an avatar for each book
Here's what concerns me a little bit, and what may be a point of discussion rather than just handled via comments on GitHub, but maybe you'll alleviate my worries immediately. I'm just wondering ... why? Wouldn't it "feel" better to have one character to progress through all the books? Usually when providing more than one avatar (like in games such as Darkest Dungeon) you create a sort of "throwaway heroes" kind of system. But - again, you may be doing that for a very specific reason.
