### ISSUE TITLE
intelligent question handling

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#46]
## Value proposition

As a student
I do not want to be asked the same questions over and over again, even if i know them 
in order to progress in my learning

## Description

No wireframe, just a way to handle the database / questionchoice

## Acceptance criteria

- [ ] save in database how often the question was answered right
- [ ] if a question was answered right 5 times, do not ask it again

## Tasks

- [ ] save in database, how often a question was answered right
- [ ] save in database, how many mistakes where made for the question
- [ ] write an algorithm that decides based on these numbers, which question is hard and which is learned 

Size: M

**Comment by CJAkkuec** [comment]
Looking good, here's a little resource for you regarding the [weighted algorithm](https://dev.to/trekhleb/weighted-random-algorithm-in-javascript-1pdc) you're planning to write. :) Just a sidenote: this might be a little difficult to test as part of QA, because weighted randomness is difficult to observe and judge.
