### ISSUE TITLE
Save User Profile

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#5]
## Value proposition

As a student
I want my progress and choices to be memorized
in order to keep working where i stopped last time

## Description

![Database-partial-2](https://user-images.githubusercontent.com/125862830/233023946-14c0420e-71a5-4bc2-afd1-a9984c79b2e8.png)

## Acceptance criteria

- [ ] the chosen Avatar should be saved
- [ ] the status of the avatar should be saved
- [ ] the User Name should be saved
- [ ] the Progress in the story should be saved

## Tasks

- [ ] create the ability to write in the database
- [ ] create the profile of the user entry

Size:

**Comment by botacode-gh** [comment]
LGTM

**Comment by CJAkkuec** [comment]
You forgot the size :).
Maybe pour some additional love into the tasks there, I'm sure there's more steps than that. Right now it looks like you're trying to squeeze "create a user profile" and "migrate the user profile data to the database" into one user story. I feel like you might benefit from thinking about database design at some point (it should probably be part of the User Story about [database migration](https://github.com/BenRodProd/capstone-project/issues/4)).

**Comment by CJAkkuec** [comment]
> create a mongodb container for users and write the user dummy data in it
If you're working locally it's a local database rather than a container. A container is a very specific thing in the devOps process. If you're working remotely it's a mongoDB Atlas database. :) (You'd also have to create a cluster for it, iirc.)

**Comment by BenRodProd** [comment]
right, i meant collection, my fault...
