### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#6]
## Value proposition

As a student
I want to be able to navigate between the library, the main game and the settings
in order to be able to use all functions

## Description

[image of wireframe]

## Acceptance criteria

- [ ] a navigation bar is shown
- [ ] the current selection is marked
- [ ] i can switch between pages by clicking on a link

## Tasks

- [ ] create navigation component
- [ ] add it in top component
- [ ] 

Size: M

**Comment by CJAkkuec** [comment]
Strictly speaking, the form and the navigation would be two different User Stories. ;) 
First the Form (Add Vocab Page), then the Navigation.

**Comment by mulewile** [comment]
> First the Form (Add Vocab Page), **then the Navigation.**
Looks good, meets @CJAkkuec 's recommendation.

**Comment by mulewile** [comment]
"First the Form (Add Vocab Page), **then the Navigation."**

_Looks good, meets @CJAkkuec 's recommendation._
