### ISSUE TITLE
Question and Answer Page

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#7]
## Value proposition

As a student
I want to get asked questions and be able to answer
in order to learn 

## Description

![Image](https://user-images.githubusercontent.com/125862830/233087237-6f001a18-778e-418e-a141-be803383fc87.png)

## Acceptance criteria

- [ ] a random question is shown
- [ ] a answer can be typed in
- [ ] it should show if a letter is right or wrong
- [ ] if the word is typed in correctly the next word should show up

## Tasks

- [ ] create dummy data of questions and answers
- [ ] create a answer and a question component and implement it into the main.js
- [ ] in the question component - display a random question
- [ ] in the answer component - create input fields for each letter of the answer
- [ ] make an indicator if the letter entered is right or wrong
- [ ] if the word is entered correctly, load the next answer and question

Size: M

**Comment by F-Kirchhoff** [comment]
Hey Ben,
Your value proposition, acceptance criteria and tasks are great, please update your wireframe that it utilizes the whole screen. maybe place the answer at the bottom of the screen and use the remaining space to display the question.
