### ISSUE TITLE
User Log In

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#8]
## Value proposition

As a student
I want to have an own account
in order to see my progress and enter the things I want to learn

## Description

![login](https://user-images.githubusercontent.com/125862830/233045547-7cdf245d-4427-4c19-9fe2-113ba73b9731.png)

## Acceptance criteria

- [ ] a username and password have to be entered
- [ ] it must be checked if a username with this password exists
- [ ] a new user can be created

## Tasks

- [ ] make a login component
- [ ] implement it at the highest level
- [ ] create two input fields, username and password
- [ ] when clicking on create new user use these fields for new user data
- [ ] write it in the database
- [ ] lead a new user to the site to choose an avatar

Size: S

**Comment by botacode-gh** [comment]
LGTM
