### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by BenRodProd** [BenRodProd/capstone-project#9]
## Value proposition

As a student
I want to see all questions entered for a topic on one page
in order to stay organized

## Description

![books](https://user-images.githubusercontent.com/125862830/233050047-61ade601-6c94-441a-b51e-7c11bcc8824b.png)

## Acceptance criteria

- [ ] a list of questions and answers is shown, all of one topic
- [ ] By clicking on one of them, I can edit them
- [ ] a button "create new wisdom" leads to the "add new wisdom" page
- [ ] the number of total questions should be shown

## Tasks

- [ ] create a component "BookOfWisdom" 
- [ ] implement it in the "edit/index.js"
- [ ] it should show all questions and answers in a vertically scrollable list
- [ ] by clicking on one it should be editable
- [ ] create a infobox, showing the total number of questions in this book
- [ ] create a link for creating a new wisdom

Size: M
